### PR TITLE
Created unittest Framework. Models covered. OrderManagement half way.

### PR DESCRIPTION
**Pull request by TimEconometrics**
So made a start for the unittests! btw I had to change the name of the exchanges folder as well to Exchanges for the imports to work in all of the files. For some reason it does not show in this pull request. But let me know what you think!

### CODE REVIEW

**Comment by tudorelu** [comment]
Thanks Tim! Yeah I did that too (change exchanges to Exchanges) - but on master - I forgot to do it on this branch too.

**Review by tudorelu — APPROVED** [review]
This is awesome. Models tests are super thorough which is perfect, and a great start to testing Order Management, which I will also contribute to.

**Comment by TimEconometrics** [comment]
Fixed the bug in toValidQuantity. Also removed the RoundToValidquantity and RoundToValidPrice. As they are duplicates of toValidQuantity and toValidPrice. Ported calls to those deleted methods to the new ones so everything in the backtester keeps working nicely.

**Review by tudorelu — APPROVED** [review]
This looks good

**Pull request merged**
